Update profile tenant
igrowker/i004-reffindr-front pull request #151
Opened 2024-11-28 22:52 UTC by GinoGallardo

2024-11-29 14:34 UTC, JackDev21 commented
Revisa los conflictos, yo estaré por aquí, te ayudo si lo necesitas.

2024-11-30 11:06 UTC, JoaquinFeola approved these changes

2024-11-30 11:07 UTC, JoaquinFeola requested changes
Hay conflictos, revisalos por favor

2024-12-01 15:43 UTC, Noobuyer approved these changes

2024-12-01 15:43 UTC, Noobuyer commented
Segmentos a revisar

2024-12-02 00:59 UTC, JoaquinFeola approved these changes

2024-12-02 02:14 UTC, JoaquinFeola approved these changes

2024-12-02 02:14 UTC, merged